import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_DRIVER = os.getenv("DATABASE_DRIVER")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_PORT = os.getenv("DATABASE_PORT")
DATABASE_NAME = os.getenv("DATABASE_NAME")

SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = int(os.getenv("SMTP_PORT"))
SMTP_USER = os.getenv("EMAIL_USERNAME")
SMTP_PASSWORD = os.getenv("EMAIL_PASSWORD")
SMTP_RECEIVER = os.getenv("EMAIL_RECEIVER")

AFRICASTALKING_USERNAME=os.getenv("AFRICASTALKING_USERNAME")
AFRICASTALKING_API_KEY=os.getenv("AFRICASTALKING_API_KEY")